// Generated by scripts/build-hisn.mjs — do not edit
import type { HisnChapterMeta } from "./types";

export const HISN_CHAPTER_INDEX: HisnChapterMeta[] = [
  {
    "chapterNumber": 1,
    "slug": "when-waking-up",
    "fileName": "ch-001",
    "itemCount": 4,
    "title": {
      "arabic": "أذكار الاستيقاظ من النوم",
      "translations": {
        "en": "When waking up"
      }
    }
  },
  {
    "chapterNumber": 2,
    "slug": "when-wearing-a-garment",
    "fileName": "ch-002",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء لبس الثوب",
      "translations": {
        "en": "When wearing a garment"
      }
    }
  },
  {
    "chapterNumber": 3,
    "slug": "when-wearing-a-new-garment",
    "fileName": "ch-003",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء لبس الثوب الجديد",
      "translations": {
        "en": "When wearing a new garment"
      }
    }
  },
  {
    "chapterNumber": 4,
    "slug": "to-someone-wearing-a-new-garment",
    "fileName": "ch-004",
    "itemCount": 2,
    "title": {
      "arabic": "الدعاء لمن لبس ثوباً جديداً",
      "translations": {
        "en": "To someone wearing a new garment"
      }
    }
  },
  {
    "chapterNumber": 5,
    "slug": "before-undressing",
    "fileName": "ch-005",
    "itemCount": 1,
    "title": {
      "arabic": "ما يقول إذا وضع الثوب",
      "translations": {
        "en": "Before undressing"
      }
    }
  },
  {
    "chapterNumber": 6,
    "slug": "before-entering-the-bathroom",
    "fileName": "ch-006",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء دخول الخلاء",
      "translations": {
        "en": "Before entering the bathroom"
      }
    }
  },
  {
    "chapterNumber": 7,
    "slug": "after-leaving-the-bathroom",
    "fileName": "ch-007",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء الخروج من الخلاء",
      "translations": {
        "en": "After leaving the bathroom"
      }
    }
  },
  {
    "chapterNumber": 8,
    "slug": "before-ablution",
    "fileName": "ch-008",
    "itemCount": 1,
    "title": {
      "arabic": "الذكر قبل الوضوء",
      "translations": {
        "en": "Before ablution"
      }
    }
  },
  {
    "chapterNumber": 9,
    "slug": "upon-completing-the-ablution",
    "fileName": "ch-009",
    "itemCount": 3,
    "title": {
      "arabic": "الذكر بعد الفراغ من الوضوء",
      "translations": {
        "en": "Upon completing the ablution"
      }
    }
  },
  {
    "chapterNumber": 10,
    "slug": "remembrance-when-leaving-the-home",
    "fileName": "ch-010",
    "itemCount": 2,
    "title": {
      "arabic": "الذكر عند الخروج من المنزل",
      "translations": {
        "en": "Remembrance when leaving the home"
      }
    }
  },
  {
    "chapterNumber": 11,
    "slug": "remembrance-upon-entering-the-home",
    "fileName": "ch-011",
    "itemCount": 1,
    "title": {
      "arabic": "الذكر عند الدخول المنزل",
      "translations": {
        "en": "Remembrance upon entering the home"
      }
    }
  },
  {
    "chapterNumber": 12,
    "slug": "when-going-to-the-mosque",
    "fileName": "ch-012",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء الذهاب إلى المسجد",
      "translations": {
        "en": "When going to the mosque"
      }
    }
  },
  {
    "chapterNumber": 13,
    "slug": "upon-entering-the-mosque",
    "fileName": "ch-013",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء دخول المسجد",
      "translations": {
        "en": "Upon entering the mosque"
      }
    }
  },
  {
    "chapterNumber": 14,
    "slug": "upon-leaving-the-mosque",
    "fileName": "ch-014",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء الخروج من المسجد",
      "translations": {
        "en": "Upon leaving the mosque"
      }
    }
  },
  {
    "chapterNumber": 15,
    "slug": "concerning-the-athan-the-call-to-prayer",
    "fileName": "ch-015",
    "itemCount": 5,
    "title": {
      "arabic": "أذكار الأذان",
      "translations": {
        "en": "Concerning the athan (the call to prayer)"
      }
    }
  },
  {
    "chapterNumber": 16,
    "slug": "at-the-start-of-the-prayer-after-takbeer",
    "fileName": "ch-016",
    "itemCount": 6,
    "title": {
      "arabic": "دعاء الاستفتاح",
      "translations": {
        "en": "At the start of the prayer (after takbeer)"
      }
    }
  },
  {
    "chapterNumber": 17,
    "slug": "while-bowing-in-prayer",
    "fileName": "ch-017",
    "itemCount": 5,
    "title": {
      "arabic": "دعاء الركوع",
      "translations": {
        "en": "While bowing in prayer"
      }
    }
  },
  {
    "chapterNumber": 18,
    "slug": "upon-rising-from-the-bowing-position",
    "fileName": "ch-018",
    "itemCount": 3,
    "title": {
      "arabic": "دعاء الرفع من الركوع",
      "translations": {
        "en": "Upon rising from the bowing position"
      }
    }
  },
  {
    "chapterNumber": 19,
    "slug": "while-prostrating",
    "fileName": "ch-019",
    "itemCount": 7,
    "title": {
      "arabic": "دعاء السجود",
      "translations": {
        "en": "While prostrating"
      }
    }
  },
  {
    "chapterNumber": 20,
    "slug": "between-the-two-prostrations",
    "fileName": "ch-020",
    "itemCount": 2,
    "title": {
      "arabic": "دعاء الجلسة بين السجدتين",
      "translations": {
        "en": "Between the two prostrations"
      }
    }
  },
  {
    "chapterNumber": 21,
    "slug": "when-prostrating-due-to-recitation-of-the-quran",
    "fileName": "ch-021",
    "itemCount": 2,
    "title": {
      "arabic": "دعاء سجود التلاوة",
      "translations": {
        "en": "When prostrating due to recitation of the Quran"
      }
    }
  },
  {
    "chapterNumber": 22,
    "slug": "the-tashahhud",
    "fileName": "ch-022",
    "itemCount": 1,
    "title": {
      "arabic": "التشهد",
      "translations": {
        "en": "The Tashahhud"
      }
    }
  },
  {
    "chapterNumber": 23,
    "slug": "prayers-upon-the-prophet-after-the-tashahhud",
    "fileName": "ch-023",
    "itemCount": 2,
    "title": {
      "arabic": "الصلاة على النبي ﷺ بعد التشهد",
      "translations": {
        "en": "Prayers upon the Prophet ﷺ after the tashahhud"
      }
    }
  },
  {
    "chapterNumber": 24,
    "slug": "after-the-last-tashahhud-and-before-salam",
    "fileName": "ch-024",
    "itemCount": 11,
    "title": {
      "arabic": "الدعاء بعد التشهد الأخير وقبل السلام",
      "translations": {
        "en": "After the last tashahhud and before salam"
      }
    }
  },
  {
    "chapterNumber": 25,
    "slug": "after-salam",
    "fileName": "ch-025",
    "itemCount": 8,
    "title": {
      "arabic": "الأذكار بعد السلام من الصلاة",
      "translations": {
        "en": "After salam"
      }
    }
  },
  {
    "chapterNumber": 26,
    "slug": "for-seeking-guidance-in-forming-a-decision-or-choosing-the-proper-course",
    "fileName": "ch-026",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء صلاة الاستخارة",
      "translations": {
        "en": "For seeking guidance in forming a decision or choosing the proper course"
      }
    }
  },
  {
    "chapterNumber": 27,
    "slug": "in-the-morning-and-evening",
    "fileName": "ch-027",
    "itemCount": 25,
    "title": {
      "arabic": "أذكار الصباح والمساء",
      "translations": {
        "en": "In the morning and evening"
      }
    }
  },
  {
    "chapterNumber": 28,
    "slug": "before-sleeping",
    "fileName": "ch-028",
    "itemCount": 13,
    "title": {
      "arabic": "أذكار النوم",
      "translations": {
        "en": "Before sleeping"
      }
    }
  },
  {
    "chapterNumber": 29,
    "slug": "when-tossing-and-turning-during-the-night",
    "fileName": "ch-029",
    "itemCount": 1,
    "title": {
      "arabic": "الدعاء إذا تقلب ليلاً",
      "translations": {
        "en": "When tossing and turning during the night"
      }
    }
  },
  {
    "chapterNumber": 30,
    "slug": "upon-experiencing-unrest-fear-apprehensiveness-during-sleep",
    "fileName": "ch-030",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء القلق والفزع في النوم ومن بلي بالوحشة",
      "translations": {
        "en": "Upon experiencing unrest, fear, apprehensiveness during sleep"
      }
    }
  },
  {
    "chapterNumber": 31,
    "slug": "upon-seeing-a-good-dream-or-a-bad-dream",
    "fileName": "ch-031",
    "itemCount": 2,
    "title": {
      "arabic": "ما يفعل من رأى الرؤيا أو الحلم",
      "translations": {
        "en": "Upon seeing a good dream or a bad dream"
      }
    }
  },
  {
    "chapterNumber": 32,
    "slug": "qunoot-al-witr",
    "fileName": "ch-032",
    "itemCount": 3,
    "title": {
      "arabic": "دعاء قنوت الوتر",
      "translations": {
        "en": "Qunoot Al-Witr"
      }
    }
  },
  {
    "chapterNumber": 33,
    "slug": "immediately-after-salam-of-the-witr-prayer",
    "fileName": "ch-033",
    "itemCount": 1,
    "title": {
      "arabic": "الذكر عقب السلام من الوتر",
      "translations": {
        "en": "Immediately after salam of the witr prayer"
      }
    }
  },
  {
    "chapterNumber": 34,
    "slug": "for-anxiety-and-sorrow",
    "fileName": "ch-034",
    "itemCount": 2,
    "title": {
      "arabic": "دعاء الهم والحزن",
      "translations": {
        "en": "For anxiety and sorrow"
      }
    }
  },
  {
    "chapterNumber": 35,
    "slug": "for-one-in-distress",
    "fileName": "ch-035",
    "itemCount": 4,
    "title": {
      "arabic": "دعاء الكرب",
      "translations": {
        "en": "For one in distress"
      }
    }
  },
  {
    "chapterNumber": 36,
    "slug": "upon-encountering-an-enemy-or-those-of-authority",
    "fileName": "ch-036",
    "itemCount": 3,
    "title": {
      "arabic": "دعاء لقاء العدو وذي السلطان",
      "translations": {
        "en": "Upon encountering an enemy or those of authority"
      }
    }
  },
  {
    "chapterNumber": 37,
    "slug": "for-one-afraid-of-the-ruler-s-injustice",
    "fileName": "ch-037",
    "itemCount": 2,
    "title": {
      "arabic": "دعاء من خاف ظلم السلطان",
      "translations": {
        "en": "For one afraid of the ruler's injustice"
      }
    }
  },
  {
    "chapterNumber": 38,
    "slug": "against-enemies",
    "fileName": "ch-038",
    "itemCount": 1,
    "title": {
      "arabic": "الدعاء على العدو",
      "translations": {
        "en": "Against enemies"
      }
    }
  },
  {
    "chapterNumber": 39,
    "slug": "when-being-afraid-of-a-group-of-people",
    "fileName": "ch-039",
    "itemCount": 1,
    "title": {
      "arabic": "ما يقول من خاف قوماً",
      "translations": {
        "en": "When being afraid of a group of people"
      }
    }
  },
  {
    "chapterNumber": 40,
    "slug": "for-one-afflicted-with-doubt-in-his-faith",
    "fileName": "ch-040",
    "itemCount": 3,
    "title": {
      "arabic": "دعاء من أصابه شك في الإيمان",
      "translations": {
        "en": "For one afflicted with doubt in his faith"
      }
    }
  },
  {
    "chapterNumber": 41,
    "slug": "settling-a-debt",
    "fileName": "ch-041",
    "itemCount": 2,
    "title": {
      "arabic": "الدعاء قضاء الدين",
      "translations": {
        "en": "Settling a debt"
      }
    }
  },
  {
    "chapterNumber": 42,
    "slug": "for-one-afflicted-by-whisperings-in-prayer-or-recitation",
    "fileName": "ch-042",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء الوسوسة في الصلاة والقراءة",
      "translations": {
        "en": "For one afflicted by whisperings in prayer or recitation"
      }
    }
  },
  {
    "chapterNumber": 43,
    "slug": "for-one-whose-affairs-have-become-difficult",
    "fileName": "ch-043",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء من استصعب عليه أمر",
      "translations": {
        "en": "For one whose affairs have become difficult"
      }
    }
  },
  {
    "chapterNumber": 44,
    "slug": "upon-committing-a-sin",
    "fileName": "ch-044",
    "itemCount": 1,
    "title": {
      "arabic": "ما يقول ويفعل من أذنب ذنباً",
      "translations": {
        "en": "Upon committing a sin"
      }
    }
  },
  {
    "chapterNumber": 45,
    "slug": "for-expelling-the-devil-and-his-whisperings",
    "fileName": "ch-045",
    "itemCount": 3,
    "title": {
      "arabic": "دعاء طرد الشيطان ووساوسه",
      "translations": {
        "en": "For expelling the devil and his whisperings"
      }
    }
  },
  {
    "chapterNumber": 46,
    "slug": "when-stricken-with-a-mishap-or-overtaken-by-an-affair",
    "fileName": "ch-046",
    "itemCount": 1,
    "title": {
      "arabic": "الدعاء حينما يقع ما لا يرضاه أو غلب على أمره",
      "translations": {
        "en": "When stricken with a mishap or overtaken by an affair"
      }
    }
  },
  {
    "chapterNumber": 47,
    "slug": "congratulation-on-the-occasion-of-a-birth-and-its-reply",
    "fileName": "ch-047",
    "itemCount": 1,
    "title": {
      "arabic": "تهنئة المولود له وجوابه",
      "translations": {
        "en": "Congratulation on the occasion of a birth and its reply"
      }
    }
  },
  {
    "chapterNumber": 48,
    "slug": "placing-childen-under-allah-s-protection",
    "fileName": "ch-048",
    "itemCount": 1,
    "title": {
      "arabic": "ما يعوذ به الأولاد",
      "translations": {
        "en": "Placing childen under Allah’s protection"
      }
    }
  },
  {
    "chapterNumber": 49,
    "slug": "when-visiting-the-sick",
    "fileName": "ch-049",
    "itemCount": 2,
    "title": {
      "arabic": "الدعاء للمريض في عيادته",
      "translations": {
        "en": "When visiting the sick"
      }
    }
  },
  {
    "chapterNumber": 50,
    "slug": "excellence-of-visiting-the-sick",
    "fileName": "ch-050",
    "itemCount": 1,
    "title": {
      "arabic": "فضل عيادة المريض",
      "translations": {
        "en": "Excellence of visiting the sick"
      }
    }
  },
  {
    "chapterNumber": 51,
    "slug": "when-the-sick-have-renounced-all-hope-of-life",
    "fileName": "ch-051",
    "itemCount": 3,
    "title": {
      "arabic": "دعاء المريض الذي يئس من حياته",
      "translations": {
        "en": "When the sick have renounced all hope of life"
      }
    }
  },
  {
    "chapterNumber": 52,
    "slug": "instruction-for-the-one-nearing-death",
    "fileName": "ch-052",
    "itemCount": 1,
    "title": {
      "arabic": "تلقين المحتضر لا إله إلا الله",
      "translations": {
        "en": "Instruction for the one nearing death"
      }
    }
  },
  {
    "chapterNumber": 53,
    "slug": "for-one-afflicted-by-a-calamity",
    "fileName": "ch-053",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء من أصيب بمصيبة",
      "translations": {
        "en": "For one afflicted by a calamity"
      }
    }
  },
  {
    "chapterNumber": 54,
    "slug": "when-closing-the-eyes-of-the-deceased",
    "fileName": "ch-054",
    "itemCount": 1,
    "title": {
      "arabic": "الدعاء عند إغماض الميت",
      "translations": {
        "en": "When closing the eyes of the deceased"
      }
    }
  },
  {
    "chapterNumber": 55,
    "slug": "for-the-deceased-at-the-funeral-prayer",
    "fileName": "ch-055",
    "itemCount": 4,
    "title": {
      "arabic": "الدعاء للميت في الصلاة عليه",
      "translations": {
        "en": "For the deceased at the funeral prayer"
      }
    }
  },
  {
    "chapterNumber": 56,
    "slug": "when-the-deceased-is-a-child-during-the-funeral-prayer",
    "fileName": "ch-056",
    "itemCount": 2,
    "title": {
      "arabic": "الدعاء للفرط في الصلاة عليه",
      "translations": {
        "en": "When the deceased is a child, during the funeral prayer"
      }
    }
  },
  {
    "chapterNumber": 57,
    "slug": "condolence",
    "fileName": "ch-057",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء التعزية",
      "translations": {
        "en": "Condolence"
      }
    }
  },
  {
    "chapterNumber": 58,
    "slug": "placing-the-deceased-in-the-grave",
    "fileName": "ch-058",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء عند إدخال الميت القبر",
      "translations": {
        "en": "Placing the deceased in the grave"
      }
    }
  },
  {
    "chapterNumber": 59,
    "slug": "after-burying-the-deceased",
    "fileName": "ch-059",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء بعد دفن الميت",
      "translations": {
        "en": "After burying the deceased"
      }
    }
  },
  {
    "chapterNumber": 60,
    "slug": "visiting-the-graves",
    "fileName": "ch-060",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء زيارة القبور",
      "translations": {
        "en": "Visiting the graves"
      }
    }
  },
  {
    "chapterNumber": 61,
    "slug": "during-a-wind-storm",
    "fileName": "ch-061",
    "itemCount": 2,
    "title": {
      "arabic": "دعاء الريح",
      "translations": {
        "en": "During a wind storm"
      }
    }
  },
  {
    "chapterNumber": 62,
    "slug": "upon-hearing-thunder",
    "fileName": "ch-062",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء الرعد",
      "translations": {
        "en": "Upon hearing thunder"
      }
    }
  },
  {
    "chapterNumber": 63,
    "slug": "for-rain",
    "fileName": "ch-063",
    "itemCount": 3,
    "title": {
      "arabic": "من أدعية الاستسقاء",
      "translations": {
        "en": "For rain"
      }
    }
  },
  {
    "chapterNumber": 64,
    "slug": "when-it-rains",
    "fileName": "ch-064",
    "itemCount": 1,
    "title": {
      "arabic": "الدعاء إذا رأى المطر",
      "translations": {
        "en": "When it rains"
      }
    }
  },
  {
    "chapterNumber": 65,
    "slug": "after-rainfall",
    "fileName": "ch-065",
    "itemCount": 1,
    "title": {
      "arabic": "الذكر بعد نزول المطر",
      "translations": {
        "en": "After rainfall"
      }
    }
  },
  {
    "chapterNumber": 66,
    "slug": "asking-for-clear-skies",
    "fileName": "ch-066",
    "itemCount": 1,
    "title": {
      "arabic": "من أدعية الاستصحاء",
      "translations": {
        "en": "Asking for clear skies"
      }
    }
  },
  {
    "chapterNumber": 67,
    "slug": "upon-sighting-the-crescent-moon",
    "fileName": "ch-067",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء رؤية الهلال",
      "translations": {
        "en": "Upon sighting the crescent moon"
      }
    }
  },
  {
    "chapterNumber": 68,
    "slug": "upon-breaking-fast",
    "fileName": "ch-068",
    "itemCount": 2,
    "title": {
      "arabic": "الدعاء عند إفطار الصائم",
      "translations": {
        "en": "Upon breaking fast"
      }
    }
  },
  {
    "chapterNumber": 69,
    "slug": "before-eating",
    "fileName": "ch-069",
    "itemCount": 2,
    "title": {
      "arabic": "الدعاء قبل الطعام",
      "translations": {
        "en": "Before eating"
      }
    }
  },
  {
    "chapterNumber": 70,
    "slug": "upon-completing-the-meal",
    "fileName": "ch-070",
    "itemCount": 2,
    "title": {
      "arabic": "الدعاء عند الفراغ من الطعام",
      "translations": {
        "en": "Upon completing the meal"
      }
    }
  },
  {
    "chapterNumber": 71,
    "slug": "of-the-guest-for-the-host",
    "fileName": "ch-071",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء الضيف لصاحب الطعام",
      "translations": {
        "en": "Of the guest for the host"
      }
    }
  },
  {
    "chapterNumber": 72,
    "slug": "to-one-who-intends-to-give-food-or-drink",
    "fileName": "ch-072",
    "itemCount": 1,
    "title": {
      "arabic": "الدعاء إذا أراد الطعام أو الشراب",
      "translations": {
        "en": "To one who intends to give food or drink"
      }
    }
  },
  {
    "chapterNumber": 73,
    "slug": "when-breaking-fast-in-someone-s-home",
    "fileName": "ch-073",
    "itemCount": 1,
    "title": {
      "arabic": "الدعاء إذا أفطر عند أهل بيت",
      "translations": {
        "en": "When breaking fast in someone’s home"
      }
    }
  },
  {
    "chapterNumber": 74,
    "slug": "by-one-fasting-when-presented-with-food-and-does-not-break-his-fast",
    "fileName": "ch-074",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء الصائم إذا حضر الطعام ولم يفطر",
      "translations": {
        "en": "By one fasting when presented with food and does not break his fast"
      }
    }
  },
  {
    "chapterNumber": 75,
    "slug": "when-insulted-while-fasting",
    "fileName": "ch-075",
    "itemCount": 1,
    "title": {
      "arabic": "ما يقول الصائم إذا سابه أحد",
      "translations": {
        "en": "When insulted while fasting"
      }
    }
  },
  {
    "chapterNumber": 76,
    "slug": "upon-seeing-the-early-or-premature-fruit",
    "fileName": "ch-076",
    "itemCount": 1,
    "title": {
      "arabic": "الدعاء عند رؤية باكورة الثمر",
      "translations": {
        "en": "Upon seeing the early or premature fruit"
      }
    }
  },
  {
    "chapterNumber": 77,
    "slug": "upon-sneezing",
    "fileName": "ch-077",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء العطاس",
      "translations": {
        "en": "Upon sneezing"
      }
    }
  },
  {
    "chapterNumber": 78,
    "slug": "when-a-disbeliever-praises-allah-after-sneezing",
    "fileName": "ch-078",
    "itemCount": 1,
    "title": {
      "arabic": "ما يقالُ للكافر إذا عطس فحمد الله",
      "translations": {
        "en": "When a disbeliever praises Allah after sneezing"
      }
    }
  },
  {
    "chapterNumber": 79,
    "slug": "to-the-newlywed",
    "fileName": "ch-079",
    "itemCount": 1,
    "title": {
      "arabic": "الدعاء للمتزوج",
      "translations": {
        "en": "To the newlywed"
      }
    }
  },
  {
    "chapterNumber": 80,
    "slug": "on-the-wedding-night-or-when-buying-an-animal",
    "fileName": "ch-080",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء المتزوج لنفسه ودعاء شراء الدابة",
      "translations": {
        "en": "On the wedding night or when buying an animal"
      }
    }
  },
  {
    "chapterNumber": 81,
    "slug": "before-sexual-intercourse-with-the-wife",
    "fileName": "ch-081",
    "itemCount": 1,
    "title": {
      "arabic": "الدعاء قبل إتيان الزوجة",
      "translations": {
        "en": "Before sexual intercourse with the wife"
      }
    }
  },
  {
    "chapterNumber": 82,
    "slug": "when-angry",
    "fileName": "ch-082",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء الغضب",
      "translations": {
        "en": "When angry"
      }
    }
  },
  {
    "chapterNumber": 83,
    "slug": "upon-seeing-someone-in-trial-or-tribulation",
    "fileName": "ch-083",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء من رأى مبتلى",
      "translations": {
        "en": "Upon seeing someone in trial or tribulation"
      }
    }
  },
  {
    "chapterNumber": 84,
    "slug": "at-a-sitting-or-gathering",
    "fileName": "ch-084",
    "itemCount": 1,
    "title": {
      "arabic": "ما يقال في المجلس",
      "translations": {
        "en": "At a sitting or gathering"
      }
    }
  },
  {
    "chapterNumber": 85,
    "slug": "for-the-expiation-of-sins-said-at-the-conclusion-of-a-sitting-or-gathering",
    "fileName": "ch-085",
    "itemCount": 1,
    "title": {
      "arabic": "كفارة المجلس",
      "translations": {
        "en": "For the expiation of sins, said at the conclusion of a sitting or gathering"
      }
    }
  },
  {
    "chapterNumber": 86,
    "slug": "returning-a-supplication-of-forgiveness",
    "fileName": "ch-086",
    "itemCount": 1,
    "title": {
      "arabic": "الدعاء لمن قال غفر الله لك",
      "translations": {
        "en": "Returning a supplication of forgiveness"
      }
    }
  },
  {
    "chapterNumber": 87,
    "slug": "to-one-who-does-you-a-favour",
    "fileName": "ch-087",
    "itemCount": 1,
    "title": {
      "arabic": "الدعاء لمن صنع إليك معروفاً",
      "translations": {
        "en": "To one who does you a favour"
      }
    }
  },
  {
    "chapterNumber": 88,
    "slug": "protection-from-the-dajjal",
    "fileName": "ch-088",
    "itemCount": 1,
    "title": {
      "arabic": "الذكر الذي يعصم الله به من الدجال",
      "translations": {
        "en": "Protection from the Dajjal"
      }
    }
  },
  {
    "chapterNumber": 89,
    "slug": "to-one-who-pronounces-his-love-for-you-for-allah-s-sake",
    "fileName": "ch-089",
    "itemCount": 1,
    "title": {
      "arabic": "الدعاء لمن قال إني أحبك في الله",
      "translations": {
        "en": "To one who pronounces his love for you, for Allah’s sake"
      }
    }
  },
  {
    "chapterNumber": 90,
    "slug": "to-one-who-has-offered-you-some-of-his-wealth",
    "fileName": "ch-090",
    "itemCount": 1,
    "title": {
      "arabic": "الدعاء لمن عرض عليك ماله",
      "translations": {
        "en": "To one who has offered you some of his wealth"
      }
    }
  },
  {
    "chapterNumber": 91,
    "slug": "to-the-debtor-when-his-debt-is-settled",
    "fileName": "ch-091",
    "itemCount": 1,
    "title": {
      "arabic": "الدعاء لمن أقرض عند القضاء",
      "translations": {
        "en": "To the debtor when his debt is settled"
      }
    }
  },
  {
    "chapterNumber": 92,
    "slug": "for-fear-of-shirk",
    "fileName": "ch-092",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء الخوف من الشرك",
      "translations": {
        "en": "For fear of shirk"
      }
    }
  },
  {
    "chapterNumber": 93,
    "slug": "to-someone-who-says-may-allah-bless-you",
    "fileName": "ch-093",
    "itemCount": 1,
    "title": {
      "arabic": "الدعاء لمن قال بارك الله فيك",
      "translations": {
        "en": "To someone who says \"May Allah bless you\""
      }
    }
  },
  {
    "chapterNumber": 94,
    "slug": "the-scorn-of-ascribing-things-to-evil-omens",
    "fileName": "ch-094",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء كراهية الطيرة",
      "translations": {
        "en": "The scorn of ascribing things to evil omens"
      }
    }
  },
  {
    "chapterNumber": 95,
    "slug": "when-mounting-an-animal-or-any-means-of-transport",
    "fileName": "ch-095",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء ركوب الدابة أو ما يقوم مقامها",
      "translations": {
        "en": "When mounting an animal or any means of transport"
      }
    }
  },
  {
    "chapterNumber": 96,
    "slug": "for-travel",
    "fileName": "ch-096",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء السفر",
      "translations": {
        "en": "For travel"
      }
    }
  },
  {
    "chapterNumber": 97,
    "slug": "upon-entering-a-town-or-village",
    "fileName": "ch-097",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء دخول القرية أو البلدة",
      "translations": {
        "en": "Upon entering a town or village"
      }
    }
  },
  {
    "chapterNumber": 98,
    "slug": "when-entering-the-market",
    "fileName": "ch-098",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء دخول السوق",
      "translations": {
        "en": "When entering the market"
      }
    }
  },
  {
    "chapterNumber": 99,
    "slug": "when-the-mounted-animal-or-mean-of-transport-stumbles",
    "fileName": "ch-099",
    "itemCount": 1,
    "title": {
      "arabic": "الدعاء إذا تعس المركوب",
      "translations": {
        "en": "When the mounted animal (or mean of transport) stumbles"
      }
    }
  },
  {
    "chapterNumber": 100,
    "slug": "supplication-of-the-traveller-for-the-resident",
    "fileName": "ch-100",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء المسافر للمقيم",
      "translations": {
        "en": "Supplication of the traveller for the resident"
      }
    }
  },
  {
    "chapterNumber": 101,
    "slug": "supplication-of-the-resident-for-the-traveller",
    "fileName": "ch-101",
    "itemCount": 2,
    "title": {
      "arabic": "دعاء المقيم للمسافر",
      "translations": {
        "en": "Supplication of the resident for the traveller"
      }
    }
  },
  {
    "chapterNumber": 102,
    "slug": "takbir-and-tasbih-during-travel",
    "fileName": "ch-102",
    "itemCount": 1,
    "title": {
      "arabic": "التكبير والتسبيح في سير السفر",
      "translations": {
        "en": "Takbir and Tasbih during travel"
      }
    }
  },
  {
    "chapterNumber": 103,
    "slug": "prayer-of-the-traveller-as-dawn-approaches",
    "fileName": "ch-103",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء المسافر إذا أسحر",
      "translations": {
        "en": "Prayer of the traveller as dawn approaches"
      }
    }
  },
  {
    "chapterNumber": 104,
    "slug": "stopping-or-lodging-somewhere-in-travel-and-otherwise",
    "fileName": "ch-104",
    "itemCount": 1,
    "title": {
      "arabic": "الدعاء إذا نزل منزلا في سفر أو غيره",
      "translations": {
        "en": "Stopping or lodging somewhere in travel and otherwise"
      }
    }
  },
  {
    "chapterNumber": 105,
    "slug": "while-returning-from-travel",
    "fileName": "ch-105",
    "itemCount": 1,
    "title": {
      "arabic": "ذكر الرجوع من السفر",
      "translations": {
        "en": "While returning from travel"
      }
    }
  },
  {
    "chapterNumber": 106,
    "slug": "what-to-say-upon-receiving-pleasing-or-displeasing-news",
    "fileName": "ch-106",
    "itemCount": 1,
    "title": {
      "arabic": "ما يقول من أتاه أمر يسره أو يكرهه",
      "translations": {
        "en": "What to say upon receiving pleasing or displeasing news"
      }
    }
  },
  {
    "chapterNumber": 107,
    "slug": "excellence-of-sending-prayers-upon-the-prophet-saws",
    "fileName": "ch-107",
    "itemCount": 5,
    "title": {
      "arabic": "فضل الصلاة على النبي ﷺ",
      "translations": {
        "en": "Excellence of sending prayers upon the Prophet (saws)"
      }
    }
  },
  {
    "chapterNumber": 108,
    "slug": "excellence-of-spreading-the-islamic-greeting",
    "fileName": "ch-108",
    "itemCount": 3,
    "title": {
      "arabic": "إفشاء السلام",
      "translations": {
        "en": "Excellence of spreading the Islamic greeting"
      }
    }
  },
  {
    "chapterNumber": 109,
    "slug": "returning-a-greeting-to-a-disbeliever",
    "fileName": "ch-109",
    "itemCount": 1,
    "title": {
      "arabic": "كيف يرد السلام على الكافر إذا سلم",
      "translations": {
        "en": "Returning a greeting to a disbeliever"
      }
    }
  },
  {
    "chapterNumber": 110,
    "slug": "upon-hearing-a-rooster-crow-or-the-braying-of-a-donkey",
    "fileName": "ch-110",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء عند سماع صياح الديك ونهيق الحمار",
      "translations": {
        "en": "Upon hearing a rooster crow or the braying of a donkey"
      }
    }
  },
  {
    "chapterNumber": 111,
    "slug": "upon-hearing-the-barking-of-dogs-at-night",
    "fileName": "ch-111",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء عند سماع نباح الكلاب بالليل",
      "translations": {
        "en": "Upon hearing the barking of dogs at night"
      }
    }
  },
  {
    "chapterNumber": 112,
    "slug": "for-one-you-have-insulted",
    "fileName": "ch-112",
    "itemCount": 1,
    "title": {
      "arabic": "الدعاء لمن سببته",
      "translations": {
        "en": "For one you have insulted"
      }
    }
  },
  {
    "chapterNumber": 113,
    "slug": "the-etiquette-of-praising-a-fellow-muslim",
    "fileName": "ch-113",
    "itemCount": 1,
    "title": {
      "arabic": "ما يقول المسلم إذا مدح المسلم",
      "translations": {
        "en": "The etiquette of praising a fellow Muslim"
      }
    }
  },
  {
    "chapterNumber": 114,
    "slug": "for-the-one-that-have-been-praised",
    "fileName": "ch-114",
    "itemCount": 1,
    "title": {
      "arabic": "ما يقول المسلم إذا زكي",
      "translations": {
        "en": "For the one that have been praised"
      }
    }
  },
  {
    "chapterNumber": 115,
    "slug": "the-talbiya-for-the-one-doing-hajj-or-umrah",
    "fileName": "ch-115",
    "itemCount": 1,
    "title": {
      "arabic": "كيف يلبي المحرم في الحج أو العمرة",
      "translations": {
        "en": "The Talbiya for the one doing Hajj or 'Umrah"
      }
    }
  },
  {
    "chapterNumber": 116,
    "slug": "the-takbir-passing-the-black-stone",
    "fileName": "ch-116",
    "itemCount": 1,
    "title": {
      "arabic": "التكبير إذا أتي الركن الأسود",
      "translations": {
        "en": "The Takbîr passing the black stone"
      }
    }
  },
  {
    "chapterNumber": 117,
    "slug": "between-the-yemeni-corner-and-the-black-stone",
    "fileName": "ch-117",
    "itemCount": 1,
    "title": {
      "arabic": "الدعاء بين الركن اليماني والحجر الأسود",
      "translations": {
        "en": "Between the Yemeni corner and the black stone"
      }
    }
  },
  {
    "chapterNumber": 118,
    "slug": "when-at-mount-safa-and-mount-marwah",
    "fileName": "ch-118",
    "itemCount": 1,
    "title": {
      "arabic": "دعاء الوقوف على الصفا والمروة",
      "translations": {
        "en": "When at Mount Safa and Mount Marwah"
      }
    }
  },
  {
    "chapterNumber": 119,
    "slug": "the-day-of-arafah",
    "fileName": "ch-119",
    "itemCount": 1,
    "title": {
      "arabic": "الدعاء يوم عرفة",
      "translations": {
        "en": "The Day of 'Arafah"
      }
    }
  },
  {
    "chapterNumber": 120,
    "slug": "remembrance-at-muzdalifa",
    "fileName": "ch-120",
    "itemCount": 1,
    "title": {
      "arabic": "الذكر عند المشعر الحرام",
      "translations": {
        "en": "Remembrance at Muzdalifa"
      }
    }
  },
  {
    "chapterNumber": 121,
    "slug": "takbir-when-throwing-each-pebble-at-the-jamarat",
    "fileName": "ch-121",
    "itemCount": 1,
    "title": {
      "arabic": "التكبير عند رمي الجمار مع كل حصاة",
      "translations": {
        "en": "Takbir when throwing each pebble at the Jamarat"
      }
    }
  },
  {
    "chapterNumber": 122,
    "slug": "at-times-of-amazement-and-that-which-delights",
    "fileName": "ch-122",
    "itemCount": 2,
    "title": {
      "arabic": "ما يقول عند التعجب والأمر السار",
      "translations": {
        "en": "At times of amazement and that which delights"
      }
    }
  },
  {
    "chapterNumber": 123,
    "slug": "upon-receiving-pleasant-news",
    "fileName": "ch-123",
    "itemCount": 1,
    "title": {
      "arabic": "ما يفعل من أتاه أمر يسره",
      "translations": {
        "en": "Upon receiving pleasant news"
      }
    }
  },
  {
    "chapterNumber": 124,
    "slug": "when-feeling-some-pain-in-the-body",
    "fileName": "ch-124",
    "itemCount": 1,
    "title": {
      "arabic": "ما يفعل ويقول من أحس وجعاً في جسده",
      "translations": {
        "en": "When feeling some pain in the body"
      }
    }
  },
  {
    "chapterNumber": 125,
    "slug": "when-in-fear-of-afflicting-something-with-an-evil-eye-from-oneself",
    "fileName": "ch-125",
    "itemCount": 1,
    "title": {
      "arabic": "ما يقول من خشي أن يصيب شيئاً بعينه",
      "translations": {
        "en": "When in fear of afflicting something with an (evil) eye from oneself"
      }
    }
  },
  {
    "chapterNumber": 126,
    "slug": "when-startled",
    "fileName": "ch-126",
    "itemCount": 1,
    "title": {
      "arabic": "ما يقال عند الفزع",
      "translations": {
        "en": "When startled"
      }
    }
  },
  {
    "chapterNumber": 127,
    "slug": "when-slaughtering-or-offering-a-sacrifice",
    "fileName": "ch-127",
    "itemCount": 1,
    "title": {
      "arabic": "ما يقول عند الذبح أو النحر",
      "translations": {
        "en": "When slaughtering or offering a sacrifice"
      }
    }
  },
  {
    "chapterNumber": 128,
    "slug": "to-ward-off-the-plot-of-the-rebellious-devils",
    "fileName": "ch-128",
    "itemCount": 1,
    "title": {
      "arabic": "ما يقول لرد كيد مردة الشياطين",
      "translations": {
        "en": "To ward off the plot of the rebellious devils"
      }
    }
  },
  {
    "chapterNumber": 129,
    "slug": "seeking-forgiveness-and-repentance",
    "fileName": "ch-129",
    "itemCount": 6,
    "title": {
      "arabic": "الاستغفار والتوبة",
      "translations": {
        "en": "Seeking forgiveness and repentance"
      }
    }
  },
  {
    "chapterNumber": 130,
    "slug": "excellence-of-tasbih-tahmid-tahlil-and-takbir",
    "fileName": "ch-130",
    "itemCount": 12,
    "title": {
      "arabic": "من فضل التسبيح والتحميد ، والتهليل ، والتكبير",
      "translations": {
        "en": "Excellence of Tasbih, Tahmid, Tahlil, and Takbir"
      }
    }
  },
  {
    "chapterNumber": 131,
    "slug": "how-the-prophet-made-tasbeeh",
    "fileName": "ch-131",
    "itemCount": 1,
    "title": {
      "arabic": "كيف كان النبي ﷺ يسبح ؟",
      "translations": {
        "en": "How the Prophet ﷺ made tasbeeh"
      }
    }
  },
  {
    "chapterNumber": 132,
    "slug": "comprehensive-types-of-good-and-manners",
    "fileName": "ch-132",
    "itemCount": 1,
    "title": {
      "arabic": "من أنواع الخير والآداب الجامعة",
      "translations": {
        "en": "Comprehensive types of good and manners"
      }
    }
  }
];
