/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTasbihRouteImport } from './routes/_app.tasbih'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppFavoritesRouteImport } from './routes/_app.favorites'
import { Route as AppChaptersRouteImport } from './routes/_app.chapters'
import { Route as AppChapterSlugRouteImport } from './routes/_app.chapter.$slug'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasbihRoute = AppTasbihRouteImport.update({
  id: '/tasbih',
  path: '/tasbih',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppChaptersRoute = AppChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => AppRoute,
} as any)
const AppChapterSlugRoute = AppChapterSlugRouteImport.update({
  id: '/chapter/$slug',
  path: '/chapter/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/chapters': typeof AppChaptersRoute
  '/favorites': typeof AppFavoritesRoute
  '/settings': typeof AppSettingsRoute
  '/tasbih': typeof AppTasbihRoute
  '/chapter/$slug': typeof AppChapterSlugRoute
}
export interface FileRoutesByTo {
  '/chapters': typeof AppChaptersRoute
  '/favorites': typeof AppFavoritesRoute
  '/settings': typeof AppSettingsRoute
  '/tasbih': typeof AppTasbihRoute
  '/': typeof AppIndexRoute
  '/chapter/$slug': typeof AppChapterSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/chapters': typeof AppChaptersRoute
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tasbih': typeof AppTasbihRoute
  '/_app/': typeof AppIndexRoute
  '/_app/chapter/$slug': typeof AppChapterSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chapters'
    | '/favorites'
    | '/settings'
    | '/tasbih'
    | '/chapter/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chapters'
    | '/favorites'
    | '/settings'
    | '/tasbih'
    | '/'
    | '/chapter/$slug'
  id:
    | '__root__'
    | '/_app'
    | '/_app/chapters'
    | '/_app/favorites'
    | '/_app/settings'
    | '/_app/tasbih'
    | '/_app/'
    | '/_app/chapter/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasbih': {
      id: '/_app/tasbih'
      path: '/tasbih'
      fullPath: '/tasbih'
      preLoaderRoute: typeof AppTasbihRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chapters': {
      id: '/_app/chapters'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof AppChaptersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chapter/$slug': {
      id: '/_app/chapter/$slug'
      path: '/chapter/$slug'
      fullPath: '/chapter/$slug'
      preLoaderRoute: typeof AppChapterSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChaptersRoute: typeof AppChaptersRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasbihRoute: typeof AppTasbihRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChapterSlugRoute: typeof AppChapterSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChaptersRoute: AppChaptersRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasbihRoute: AppTasbihRoute,
  AppIndexRoute: AppIndexRoute,
  AppChapterSlugRoute: AppChapterSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
